name: MurderMystery
main: io.github.mebsic.murdermystery.MurderMysteryPlugin
version: 0.1
depend: [Hycopy]
softdepend: [Citizens]
commands:
  start:
    usage: /start
  token:
    usage: /token <player> <amount>
  togglehints:
    usage: /togglehints
  whoismurderer:
    usage: /whoismurderer
  whoisdetective:
    usage: /whoisdetective
  getrole:
    usage: /getrole <player>
